### ISSUE TITLE
Please consider documenting parameters and adding more examples.

### ISSUE THREAD

**Issue by ioctl-user** [Jaded-Encoding-Thaumaturgy/vs-denoise#108]
For now it's difficult start working with the project.

The MVTools.denoise() get a lot of parameters, which have not obvious meaning.

Please consider adding parameters description and short usage guide (which is the best/fast for anime, movie, live movie ...) to the README.md.

And also please add example of preset usage (NOISY, FAST, ...).

**Comment by wiwaz** [comment]
> The MVTools.denoise() get a lot of parameters, which have not obvious meaning.

All these functions do is wrap around the mvtools plugin, please see mvtools doc for more information.

**Comment by ioctl-user** [comment]
> > The MVTools.denoise() get a lot of parameters, which have not obvious meaning.
> 
> All these functions do is wrap around the mvtools plugin, please see mvtools doc for more information.

May you adding link to the project README for other people?

**Comment by ioctl-user** [comment]
There is still no link to the MVTool documentation in the README file.
