### ISSUE TITLE
Ambiguous parameter names with nl_means

### ISSUE THREAD

**Issue by emotion3459** [Jaded-Encoding-Thaumaturgy/vs-denoise#131]
Perhaps skill issue, but to me the nl_means parameter names are too ambiguous and lead to mistaking one for another.

Specifically simr and sr sound very similar yet do completely different things, perhaps there could be some consideration on better naming.

**Comment by LightArrowsEXE** [comment]
What we can do for the time being is change the param names, accept kwargs, and pop the current param names (that were changed) and throw a deprecation warning if any exist?
