### ISSUE TITLE
BM3DCPU won't allow Profile.VERY_NOISY because of CUDA

### ISSUE THREAD

**Issue by Mikewando** [Jaded-Encoding-Thaumaturgy/vs-denoise#133]
```py
from vstools import vs, initialize_clip, set_output
from vsdenoise import BM3DCPU, Profile

clip = vs.core.std.BlankClip(format=vs.YUV420P16)
clip = initialize_clip(clip)
clip = BM3DCPU.denoise(clip, profile=Profile.VERY_NOISY)
set_output(clip)

# Results in ValueError: Profile "VERY_NOISY" is not supported! (BM3DCuda)
```

It seems like `final()` only evaluates truthiness of `elif not cuda` but as far as I can tell the plugin is passed and `core.lazy.bm3dcpu` is truthy so the non-CUDA conditional branch is never taken.

**Comment by Setsugennoao** [comment]
BM3DCPU and BM3DCUDA have the same implementation/logic which doesn't allow for that preset

**Comment by Mikewando** [comment]
Then https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise/blob/b08faf3ee7ae909ca5e912b63c88d0bf39494d3d/vsdenoise/bm3d.py#L533 should just pass `True` instead of `self.plugin`. And the error message should be more clear about the classes which do and don't support it.
