### ISSUE TITLE
MVTools functions support

### ISSUE THREAD

**Issue by NSQY** [Jaded-Encoding-Thaumaturgy/vs-denoise#69]
- [x] Super
- [x] Analyse
- [x] Recalculate
- [x] Compensate
- [x] Degrain
- [x] Mask
- [x] Finest
- [x] Flow
  * A lesser used function from mvtools. Low priority, I've only ever seen this used once or twice.
  From [docs](https://htmlpreview.github.io/?https://github.com/pinterf/mvtools/blob/mvtools-pfmod/Documentation/mvtools2.html): `Do a motion compensation of the frame not by blocks (like MCompensate), but by pixels`.
- [x] FlowBlur
- [x] FlowInter
- [x] FlowFPS
- [x] BlockFPS
- [x] SCDetection
- [ ] DepanAnalyse
- [ ] DepanEstimate
- [ ] DepanCompensate
- [ ] DepanStabilise

**Comment by adworacz** [comment]
Also note that the latest (git) version of MVTools (not floating point) supports up to Degrain4-6 now. I added it back on new years. 

I'm not sure if that requires any code changes in this package, just wanted to give a heads up.

I'm still working on some other (mostly speed) improvements, particularly when working on higher bit depths.

**Comment by adworacz** [comment]
Totally fair. I hope to have a few more tweaks made in the coming weeks (ideally less), and then I think cutting a new release would be appropriate.

And I looked at the code in this repo. If I'm reading things right, it all should "just work", unless I missed something big. Props to how you've written the code (and the crazy dynamic nature of Python).

**Comment by adworacz** [comment]
Also @NSQY - It appears that `Recalculate` support does exist: https://github.com/Irrational-Encoding-Wizardry/vs-denoise/blob/master/vsdenoise/mvtools.py#L770-L772

So you can update the checklist.

**Comment by Setsugennoao** [comment]
> Totally fair. I hope to have a few more tweaks made in the coming weeks (ideally less), and then I think cutting a new release would be appropriate.
> 
> And I looked at the code in this repo. If I'm reading things right, it all should "just work", unless I missed something big. Props to how you've written the code (and the crazy dynamic nature of Python).

Yeah, i will have to update the check of temporal radius from 3 to 6 and hmm i think i'll be it.

**Comment by Setsugennoao** [comment]
> Also @NSQY - It appears that `Recalculate` support does exist: https://github.com/Irrational-Encoding-Wizardry/vs-denoise/blob/master/vsdenoise/mvtools.py#L770-L772
> 
> So you can update the checklist.

I actually made the checklist based on his initial issue, but i want to have a way of actually manually refining the vector data, I'll have to see and decide the API.

**Comment by adworacz** [comment]
Just an FYI, I’ve started the TemporalDegrain2 port. Nothing to submit just yet, and I’ve got a ways to go, but the MVTools class definitely helps to shrink thinks nicely.

**Comment by Setsugennoao** [comment]
Super is now decoupled and can be freely used thanks to @adworacz.

**Comment by Setsugennoao** [comment]
> Totally fair. I hope to have a few more tweaks made in the coming weeks (ideally less), and then I think cutting a new release would be appropriate.
> 
> And I looked at the code in this repo. If I'm reading things right, it all should "just work", unless I missed something big. Props to how you've written the code (and the crazy dynamic nature of Python).

![image](https://user-images.githubusercontent.com/41454651/221435480-b8bf22c5-28e2-45db-9bee-61234a425bf4.png)
Yup, just to confirm, this is the only place where radius support is checked for the int mvtools plugin.

**Comment by wiwaz** [comment]
vs-deinterlace depends on FlowInter, so adding this should be a priority IMO.
